
#========== Dev environment ======================
#   - build from source code
#   - live changes possible
#   - ports exposed (mongo, redis etc.)
#   - local env files
#   - debugging friendly
# =============Production environment ===============
# - pre-built Docker images
# - no source code
# - minimal ports exposed
# - secure env handling
# - optimized performance

# This is used in Staging deploy 
services:

  nginx:
    image: deluxdeepak/scalex-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - nginx_cache:/var/cache/nginx

  backend:
    image: deluxdeepak/scalex-backend:staging
    depends_on:
      - mongo
      - redis
      - minio
    restart: always
    env_file: .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio_data:/data
    env_file: .env

volumes:
  mongo_data:
  redis_data:
  minio_data:
  nginx_cache: