
#========== Dev environment ======================
#   - build from source code
#   - live changes possible
#   - ports exposed (mongo, redis etc.)
#   - local env files
#   - debugging friendly
# =============Production environment ===============
# - pre-built Docker images
# - no source code
# - minimal ports exposed
# - secure env handling
# - optimized performance

# This is used in Staging deploy 
services:
  backend:
    image: deluxdeepak/scalex-backend:staging
    restart: always
    env_file: .env.staging
    ports:
      - "127.0.0.1:4000:4000"

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio_data:/data
    env_file: .env.staging

volumes:
  mongo_data:
  redis_data:
  minio_data:
  nginx_cache: