
#========== Dev environment ======================
#   - build from source code
#   - live changes possible
#   - ports exposed (mongo, redis etc.)
#   - local env files
#   - debugging friendly
# =============Production environment ===============
# - pre-built Docker images
# - no source code
# - minimal ports exposed
# - secure env handling
# - optimized performance

# Compose se pull hoga but locally jo rehega wahi run hote rehega new image nahi ayega 

services:

  nginx:
    image: deluxdeepak/scalex-frontend:${TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - nginx_cache:/var/cache/nginx

  backend:
    image: deluxdeepak/scalex-backend:${TAG}
    depends_on:
      - mongo
      - redis
      - minio
    restart: always
    env_file: .env


    # Injecting direct env in production 
    # environment:
    #   NODE_ENV: production
    #   PORT: ${PORT}

    #   MongoUri: ${MONGO_URL}
    #   RedisUri: ${REDISH_URL}

    #   # MinIO
    #   MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    #   MINIO_ACCESS_KEY: ${MINIO_ACCESS}
    #   MINIO_SECRET_KEY: ${MINIO_SECRET}

    #   STORAGE_BUCKET:  ${STORAGE_BUCKET}
    #   FILE_BASE_URL:  ${FILE_BASE_URL}

    #   # Auth
    #   JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    #   JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio_data:/data
    env_file: .env

volumes:
  mongo_data:
  redis_data:
  minio_data:
  nginx_cache: