version: "3.9"
name: ScaleX-commerce

# - Backend is locally and service is in docker 
services:
  
  redis:
    image: redis:7
    environment:
      - NODE_ENV=development
      - DOCKER=true
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ScaleX-Commerce
  
  mongo:
    image: mongo
    environment:
      - NODE_ENV=development
      - DOCKER=true
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ScaleX-Commerce

  minio:
    image: minio/minio
    container_name: minio
    restart: always

    command: server /data --console-address ":9001"

    environment:
      NODE_ENV: development
      DOCKER: "true"
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data
    networks:
      - ScaleX-Commerce
  
volumes:
  minio_data:
  mongo_data:

networks:
  ScaleX-Commerce:
    driver: bridge