worker_processes auto;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    # Cache path define karo
    proxy_cache_path /var/cache/nginx levels=1:2 use_temp_path=off keys_zone=my_cache:10m inactive=60m max_size=1g ;
    upstream backend {
        server backend:3000;

    }

    server {
        # ServerBlock cache enable karo

        listen 80;
        listen 8000;

        location / {
            proxy_pass http://backend;

            proxy_cache my_cache;
            # Agar response status 200 hai → to cache me 1 minute ke liye store karo
            proxy_cache_valid 200 5m;
            proxy_cache_valid 404 1m;

            # ===========✅ stale cache serve karna
            # ===========✅ zero downtime cache
            # error
            # Backend error de raha → cache use karo
            # timeout
            # Backend slow hai → cache use karo
            # updating
            # Cache expire ho gaya hai, but backend se new data aa raha hai
            proxy_cache_use_stale error timeout updating;

            # Debugging ke liye hai (Ye header show karta hai )
            add_header X-Cache $upstream_cache_status;
        }

        location /api/products {

            proxy_pass http://backend;

            proxy_cache my_cache;
            proxy_cache_valid 200 60s;

        }

        location /api/home {

            proxy_pass http://backend;
            proxy_cache my_cache;
            proxy_cache_valid 200 30s;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_404;
            add_header X-Cache $upstream_header_time always;

        }

        location /api/search {

            proxy_pass http://backend;
            proxy_cache my_cache;
            proxy_cache_valid 200 20s;

        }
    }
}