# Use build command 
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Copy the index file from build to html of nginix  
# - dit build inside the wroking directory 
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80