# # - this will runs on real url  after deployment done 
# # dev->build image(push)->staging deploy(change the tag of the image (like :stagign )) ->integration test->e2e -> production

# name: ScaleX-commerce e2e-Tets

# on:
#   push:
#     branches:
#       - staging
#   workflow_run:
#     workflows: ["ScaleX-commerce to Staging Deploy"]
#     types:
#       - completed
# # on:
# #   push:
# #     branches:
# #       - staging

# jobs:
#   e2e:
#     runs-on: ubuntu-latest
  
#     steps:
#       - name: Ceckout branch Code
#         uses: actions/checkout@v6
#       - name: Setup Node.js
#         uses: actions/setup-node@v6
#         with: 
#           node-version: 24
#           cache: 'npm'
      
#       - name: Install root deps
#         run: npm ci

#       - name: Create .env.docker
#         run: |
#           mkdir -p Backend
#           echo "NODE_ENV=test" >> Backend/.env.docker
#           echo "PORT=4000" >> Backend/.env.docker
#           echo "CLIENT_URL=http://localhost:5173" >> Backend/.env.docker
#           echo "MONGO_URL=mongodb://mongo:27017" >> Backend/.env.docker
#           echo "REDISH_URL=redis://redis:6379" >> Backend/.env.docker
#           echo "MINIO_ENDPOINT=http://minio:9000" >> Backend/.env.docker
#           echo "MINIO_ACCESS=minioadmin" >> Backend/.env.docker
#           echo "MINIO_SECRET=minioadmin" >> Backend/.env.docker
#           echo "STORAGE_BUCKET=devbucket" >> Backend/.env.docker
#           echo "FILE_BASE_URL=http://minio:9000/devbucket" >> Backend/.env.docker
#           echo "JWT_ACCESS_SECRET=testsecret" >> Backend/.env.docker
#           echo "JWT_REFRESH_SECRET=testsecret" >> Backend/.env.docker  

#       # start the docker service 
#       - name: Start Docker
#         run: docker compose -f docker-compose.e2e.yml up -d --build

#       # Wait for frontend and wait for backend 
#       - name: Wait for frontend
#         run: |
#           until curl -f http://localhost:5173; do sleep 2; done

#       - name: Wait for backend Health check
#         run: |
#           until curl -f http://localhost:4000/api/health; do sleep 2; done

#       # Install browser for E2e test 
#       - name: Install Playwright browser 
#         run: npx playwright install --with-deps

#       # Runs all test 
#       - name: Run e2e Test 
#         run: npm run test:e2e

        
