# Test Orchestration kya hota hai?
# Ek master workflow (test.yml) jo decide karta hai:
# - kya pehle chalega
# - kya baad me chalega
# - kaun fail hua to aage rukna hai
# ===========orchestration flow =================

# Integration (Docker + services)--sun check karo api test ho reha hai ki nahi 
# Backend → Frontend → Integration → E2E → Deploy
name: Orchestration for Project E-commerce

# =========Workflow types ================
# Normal workflow(direct trigger hota hai (push pe run hota hai))
# on:
#   push:

# Reusable workflow(dusre workflow se call hota hai)
# on:
#   workflow_call:
# ========================================

on:
  push:
    branches:
      - main

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  integration:
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out 
        uses: actions/checkout@v6

      - name: Start Docker Services
        run: docker-compose up -d

      # System check karega Network call karega (fetch and axios use karega real )
      - name: Run Integration Tests
        run: npm run test:integration
