# Test Orchestration kya hota hai?
# Ek master workflow (test.yml) jo decide karta hai:
# - kya pehle chalega
# - kya baad me chalega
# - kaun fail hua to aage rukna hai
# ===========orchestration flow =================

# Integration (Docker + services)--sun check karo api test ho reha hai ki nahi 
# Backend → Frontend → Integration → E2E → Deploy
name: Orchestration for Project E-commerce

# =========Workflow types ================
# Normal workflow(direct trigger hota hai (push pe run hota hai))
# on:
#   push:

# Reusable workflow(dusre workflow se call hota hai)
# on:
#   workflow_call:
# ========================================

# Github Environment ====================
# - Environment secrets : Secrets are encrypted environment variables.
# - Environment variables: Variables are used for non-sensitive configuration data. 
# ==========================================

on:
  push:
    branches:
      - main

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  integration:
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out 
        uses: actions/checkout@v6

      # Setup node env 
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: 24
          cache: 'npm'

      - name: Create .env.docker
        run: |
          mkdir -p Backend
          echo "NODE_ENV=test" >> Backend/.env.docker
          echo "CLIENT_URL=http://localhost:5173" >> Backend/.env.docker
          echo "MONGO_URL=mongodb://mongo:27017" >> Backend/.env.docker
          echo "REDISH_URL=redis://redis:6379" >> Backend/.env.docker
          echo "MINIO_ENDPOINT=http://minio:9000" >> Backend/.env.docker
          echo "MINIO_ACCESS=minioadmin" >> Backend/.env.docker
          echo "MINIO_SECRET=minioadmin" >> Backend/.env.docker
          echo "STORAGE_BUCKET=devbucket" >> Backend/.env.docker
          echo "FILE_BASE_URL=http://minio:9000/devbucket" >> Backend/.env.docker
          echo "JWT_ACCESS_SECRET=testsecret" >> Backend/.env.docker
          echo "JWT_REFRESH_SECRET=testsecret" >> Backend/.env.docker

      - name: Check docker version
        run: docker --version
      
      - name: Check docker Compose version
        run: docker compose version

      # Skip if limit cross of pulls 
      - name: Start Docker Services
        run: docker compose -f docker-compose.integration.yml up -d --build

      # Check the route 
      - name: Wait for Backend Check-route 
        run: |
          until curl -f http://localhost:4000/api/health; do sleep 2; done
     
      # Install deps then run test (root deps install )
      - name: Install deps
        run: npm ci

      # Ye backend run kar sakta hai (backend deps install)
      # ---Backend docker kar reha hai to yehan install nahi karna hai oska deps
      # - name: Install backend deps
      #   run: npm ci --prefix Backend

      # System check karega Network call karega (fetch and axios use karega real )
      - name: Run Integration Tests
        run: npm run test:integration

      - name: Stop services
        if: always()
        run: docker compose down

  e2e:
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out 
        uses: actions/checkout@v6
      
      # Setup node js 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' 

      - name: Create .env.docker
        run: |
          mkdir -p Backend
          echo "NODE_ENV=test" >> Backend/.env.docker
          echo "CLIENT_URL=http://localhost:5173" >> Backend/.env.docker
          echo "MONGO_URL=mongodb://mongo:27017" >> Backend/.env.docker
          echo "REDISH_URL=redis://redis:6379" >> Backend/.env.docker
          echo "MINIO_ENDPOINT=http://minio:9000" >> Backend/.env.docker
          echo "MINIO_ACCESS=minioadmin" >> Backend/.env.docker
          echo "MINIO_SECRET=minioadmin" >> Backend/.env.docker
          echo "STORAGE_BUCKET=devbucket" >> Backend/.env.docker
          echo "FILE_BASE_URL=http://minio:9000/devbucket" >> Backend/.env.docker
          echo "JWT_ACCESS_SECRET=testsecret" >> Backend/.env.docker
          echo "JWT_REFRESH_SECRET=testsecret" >> Backend/.env.docker  

      # e2e me bhi docker start karna parega (Backend and frontend dono run hona chiye ) tabhi playwright chalgea 
      - name: Start Docker
        run: docker compose -f docker-compose.e2e.yml up -d --build

      # Install root deps 
      - name: Install root deps
        run: npm ci

      # Wait for backend and frontend to react ============
      - name: Wait for services
        run: |
          until curl -f http://localhost:4000/api/health; do sleep 2; done
          until curl -f http://localhost:5173; do sleep 2; done
      
      # Frontend deps and backend deps install (not need to install )
      # - name: Install frontend deps
      #   run: npm ci --prefix Front-end
      
      # - name: Install backend deps
      #   run: npm ci --prefix Backend

      
      
      # Install browser for e2e test 
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
    
      # Backend and frontend and integration test kar liye hai 
      # then only e2e test karo 
      - name: Run e2e test 
        run: npm run test:e2e
